### ISSUE TITLE
Transcript as struct

### ISSUE THREAD

**Issue by zitnik** [xlab-si/emmy#33]
Currently, type Credential is implemented as struct with, among others, fields T1 and T2 as arrays of big.Int: ([https://github.com/xlab-si/emmy/blob/master/crypto/pseudonymsys/org_issue.go#L28](url))
```go
type Credential struct {
	SmallAToGamma *big.Int
	SmallBToGamma *big.Int
	AToGamma      *big.Int
	BToGamma      *big.Int
	T1            []*big.Int
	T2            []*big.Int
}
```
If I'm not wrong, the T1 and T2 arrays always hold the same structure (A, B, Hash, ZAlpha).
In my opinion, they should be represented as struct instead of big.Int arrays.

The obvious arguments are type safety and code readability.
Another reason (and the reason I came across this problem) is the binding to Java code, where arrays of strings are not supported (strings are used instead of big.Int for ease of conversion). Because of this, mobile library currently doesn't fully support the Credential type.

I propose to create a `type Transcript struct` holding A, B, Hash, ZAlpha values, and use this type in `Credential`.

**Comment by mancabizjak** [comment]
Thanks for pointing this out @zitnik! This makes perfect sense.

 The fact that the bindings to Java code were incomplete because of this totally escaped me, and this definitely has to be dealt with. Indeed, when dealing with the bindings, I was not really focusing what's actually stored in those `[]*big.Int`s, so thanks for digging this up 🙂

I'll prepare a PR shortly, unless @miha-stopar has objections? :)
