### ISSUE TITLE
Consider mage.go to replace Makefile

### ISSUE THREAD

**Issue by gedw99** [xlab-si/emmy#87]
It makes it easy to run make on all desktops and you CI.
That's because it's just golang.
You can run it compiled of interpreted ( like make files).
It just needs a golang install.

I got it working with vgo to replace deposit also. 

Solved a ton of little issues and now runs everywhere consistently everywhere.

https://github.com/magefile/mage

https://godoc.org/golang.org/x/vgo

See tour of vgo to get started.

I plan to put up an example repo but it's not yet separated from lots of other crap.

**Comment by gedw99** [comment]
https://github.com/golang/vgo

**Comment by janhartman** [comment]
I don't see a good reason to switch to Mage as our Makefile isn't too complicated. I agree that it removes the inconvenience of needing to have make installed, but

**Comment by janhartman** [comment]
I don't see a good reason to switch to Mage as our Makefile isn't too complicated. I agree that using it removes the inconvenience of needing to have make installed (which is mostly a problem on Windows), but it does add another dependency. 

As the docs state, vgo is still a very early prototype. Dep, on the other hand, is more mature and safe for production use. For now, I would avoid vgo because of the potential issues - maybe we could make the switch when it becomes stable and potentially replaces dep.

**Comment by gedw99** [comment]
how to run a Makefile on Windows ? You can but its painful.

VGO is new. SO far i have hit no issues and when i do they fix them in 1
day.

G

**Comment by gedw99** [comment]
this is a helepr file for mage if you decide later to use it. I use this.
there are a ton of others as golang pkgs and so it makes all your build
workfows as easy a go import.

https://github.com/zvelo/zmage

**Comment by janhartman** [comment]
[WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) is a great way to run tools like make on Windows. Thank you for the helper file - it will be helpful if we decide to use mage.
I'd rather see we encounter as few issues as possible with a dependency management tool - for now, dep is probably the best choice for this project.

**Comment by gedw99** [comment]
Does not help because you dont have proper access to the windows system.
Been there and done that.

anyway...
