### ISSUE TITLE
HTTP / REST API

### ISSUE THREAD

**Issue by KrishnaPG** [xlab-si/emmy#96]
From the ReadMe it looks like it has built-in client-server model support. But not clear if it supports the clients over HTTP. Would be great if it can be made to work with HTTP/REST API.

**Comment by mancabizjak** [comment]
All the client-server communication goes through HTTP. However, as we're using gRPC, we rely on the HTTP/2 version of the protocol to support bidirectional streams of data between the client and the server. We use bidirectional streaming to simplify (and optimize) the exchange of multiple messages within a single proof or within protocols comprising anonymous authentication schemes, in a particular order.

Unfortunately, the usage of bidirectional streaming proved to be a problem when trying to use translator solutions like [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway), [grpc-websocket-proxy](https://github.com/tmc/grpc-websocket-proxy) and [grpc-web](https://github.com/grpc/grpc-web) (the latter is apparently the way to go); we experimented with all of these in an effort to enable RESTful APIs in front of our gRPC services, but the projects do not fully support (or even see it possible to truly support) bidirectional streaming.

So, the lack of a translator solution that would support bidirectional streams is the reason we decided to leave behind the idea of having RESTful APIs for our services.

**Comment by KrishnaPG** [comment]
Thanks for the very clear explanation @mancabizjak So, does that mean only go clients will be able to benefit from this library? or do you see any way others (such as JS from browser) can take advantage of this functionality?

**Comment by mancabizjak** [comment]
Sure thing! _In theory_, clients in any of the languages supported by gRPC (see [here](https://grpc.io/about/#osp)) could benefit from the library. On the practical side however, client logic inevitably relies on math and crypto functionality implemented in the `crypto` packages, which means that not only communication layer, but also (at least some of) math/crypto functionality may need to be rewritten in the chosen language. The practicality of creating an emmy client in an arbitrary language would depend on the complexity of that particular client (since we have different clients for running different protocols/proofs  of varying complexity).

At the moment, Go clients are the most up-to-date. We also have a `client/compatibility` package that can be used with the `gomobile` tool in order to create client code bindings for Java/Objective C, for usage within Android/iOS mobile apps. But it is a very limited version, and it's currently not up-to-date with the parent `client` package.

As for using the clients and crypto library from browser, I think our colleague @janhartman can elaborate more on the topic, as he was experimenting with all of the projects mentioned earlier, and more :slightly_smiling_face: AFAIK it's a bit tricky...

**Comment by janhartman** [comment]
The best way to run clients in a browser would probably be to compile to [WebAssembly](https://developer.mozilla.org/en-US/docs/WebAssembly) since [Go 1.11 just added experimental support](https://blog.golang.org/go1.11) for it. The math and crypto functionality would not need to be implemented again and I'm fairly confident it would work in a browser. However, using the Go implementation of gRPC in a browser would probably be problematic and you would likely have to implement the communication yourself by using [grpc-web](https://github.com/grpc/grpc-web) or something similar.
